Labs production refactor
LambdaSchool/mission-control-be pull request #5
Opened 2020-04-03 21:02 UTC by berniedurfee

# Description
Refactoring in prep for production launch

2020-04-07 13:14 UTC, jessmartin commented
This looks awesome @berniedurfee! 😍 I'll definitely be digging into this soon to give it a second set of eyes. 

Without having gone through it line-by-line, it seems like a lot of these are breaking changes that we'll need to push back to the student repo. Is that what you're thinking?

2020-04-09 16:59 UTC, berniedurfee commented
Lots of breaking changes, yes. In fact, lots of the functionality is still broken and needs to be updated. I'm going to push more stuff into this PR to get all the functionality working, but with an updated data model and logic.

2020-04-11 00:15 UTC, tinomen requested changes
Wow, some great changes in here. I hadn't known about winston logger and it's great to see the prisma client mock.

2020-04-11 00:15 UTC, tinomen commented on apollo/src/context/__mocks__/index.js
> +// Generate Jest mock for the context module
Wow, Could you put a video together of setting up testing for prismatopia. Having mocks sure would help.

2020-04-11 00:15 UTC, tinomen commented on apollo/src/datasources/GitHubAPI.js
> +          name,
Isn't this an ESLint standard? ;)

2020-04-11 00:15 UTC, tinomen commented on apollo/src/index.js
> +      console.log('%O', err);
No winston logger?

2020-04-11 00:15 UTC, tinomen commented on apollo/src/index.js
> +      // Don't give the specific errors to the client.
The error is being passed through this callback function. Was there an intent to replace the err with something that doesn't have the specific error?

2020-04-11 00:15 UTC, tinomen commented on apollo/src/resolvers/Note.js
> +// const attendedBy = (parent, args, context) => {
Any particular reason you committed commented out code? ;)

2020-04-11 00:15 UTC, tinomen commented on apollo/src/resolvers/Person.js
> +// const role = (parent, args, context) => {
My eyes! 🤕 #commented-out-code

2020-04-11 00:15 UTC, tinomen commented on apollo/src/resolvers/Product.js
> +/**
BTW These function docs are awesome. Thank you.

2020-04-11 00:15 UTC, tinomen commented on apollo/src/resolvers/Product.js
> +// const grades = async (parent, args, context) => {
This commented out code is less awesome. 😆

2020-04-11 00:15 UTC, tinomen commented on apollo/src/resolvers/Project.js
>    return res;
Should we replace all of these with a single line similar to `apollo/src/resolvers/Program.js`?
```suggestion
  return context.prisma.project({ id: parent.id }).product();
```

2020-04-11 00:15 UTC, tinomen commented on apollo/src/schema.js
> +  # type Label {
worth keeping?

2020-04-11 00:15 UTC, tinomen commented on prisma/seed.js
> +/* eslint-disable no-await-in-loop */
This is brilliant!

2020-04-20 19:58 UTC, merged

2020-04-20 20:17 UTC, jessmartin commented
![Very Nice](https://media.giphy.com/media/l0HTYUmU67pLWv1a8/giphy.gif)